
== Chapter 6: Deployment Pipelines

=== 6.1 Skaffold

**Slides**

. What is deployment pipeline?
. What is Skaffold?
.. Key benefits
.. Workflow

**Code**

https://github.com/GoogleContainerTools/skaffold[Skaffold] is a command line utility that facilitates continuous development for Kubernetes applications. With Skaffold, you can iterate on your application source code locally then deploy it to a remote Kubernetes cluster.

. Check context:

	kubectl config get-contexts
	CURRENT   NAME                               CLUSTER                       AUTHINFO                           NAMESPACE
	*         arun@myeks.us-east-1.eksctl.io     myeks.us-east-1.eksctl.io     arun@myeks.us-east-1.eksctl.io     
	          docker-for-desktop                 docker-for-desktop-cluster    docker-for-desktop

. Change to use local Kubernetes cluster:

	kubectl config use-context docker-for-desktop

. Download Skaffold:

	brew install skaffold

. Open http://localhost:8080/hello in browser. This will show that the page is not available.
. Copy `manifests/standalone/greeting.yaml` to `app` directory
. Run Skaffold in the application directory:

    cd app
    skaffold dev

. Refresh the page in browser to see the output.

Same Java application, now continuously built through Skaffold and deployed to a local Kubernetes cluster. This can also be integrated with Jib. This can also be deployed to a remote Kubernetes cluster.

=== 6.3 AWS CodePipeline

**Slides**

. Code Pipeline + Code Commit
.. Key benefits
.. Workflow

**Prereq**

. Create GitHub access token

**Code**

https://eksworkshop.com/codepipeline/codepipeline/

. Create IAM role
. Modify aws-auth ConfigMap
. Talk about GitHub access token
. Create CodePipeline
. https://console.aws.amazon.com/codesuite/codepipeline/pipelines[Show CodePipline]
. Tail logs
. Use the following command to access the service:

	curl http://$(kubectl get svc/hello-k8s -o jsonpath='{.status.loadBalancer.ingress[0].hostname}’)

Same Java application, now continuously built through AWS CodePipeline and deployed to an Amazon EKS cluster.

